name: CI/CD Polling App

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Клонирование репозитория
        uses: actions/checkout@v3

      - name: 🐳 Установка Docker и docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install docker.io docker-compose -y
          sudo systemctl start docker
          sudo usermod -aG docker $USER

      - name: 🔧 Построение и запуск docker-compose
        run: |
          docker-compose -f docker-compose.yml up --build -d

      - name: 🔍 Проверка статуса API
        run: |
          sleep 10  # ожидание запуска контейнеров
          curl --fail http://localhost:8000/ || (echo "API не отвечает" && exit 1)
